---
# file: appservers.yml
- hosts: appservers-1
  remote_user: "{{ ansible_ssh_user }}"
  sudo: yes
  roles:
      - common
#      - { role: openjdk, when "java_type == 'open'"}
      - { role: java, when: "java_type == 'sun'"}
      - tomcat
      - { role: elasticsearch }
