---
# file: local.yml
- hosts: localhost
  remote_user: vagrant
  sudo: yes
  roles:
    - common
    - { role: java, when: "java_type == 'sun'"}
    - tomcat
    - { role: geerlingguy.elasticsearch }
    - geerlingguy.nodejs
    - mongodb
