---
# Red Hat specific tasks
- name: Install npm and node via EPEL yum repo
  yum: name=npm enablerepo=epel state=present

- name: Install global packages
  npm: global=yes name={{ item }} state=present
  with_items: nodejs_global_packages
